# -*- coding: utf-8 -*-
"""Constantes del protocolo Argos (versión 2026.10.02.1028). Verificar contra el protocolo vigente al iniciar cada revisión."""
PROTOCOLO_BASE="2026.10.02.1028"
NOMBRES={1: 'Necesidad institucional', 2: 'Competencia del área requirente', 3: 'Justificación de la contratación', 4: 'Definición del objeto', 5: 'Requerimientos técnicos', 6: 'Congruencia necesidad-objeto', 7: 'Previsión de la contratación', 8: 'Suficiencia presupuestaria', 9: 'Oportunidad de la suficiencia', 10: 'Correspondencia de montos', 11: 'Partida y fuente', 12: 'Existencia de investigación', 13: 'Procedencia de excepción', 14: 'Fuentes consultadas', 15: 'Solicitudes de cotización', 16: 'Respuestas recibidas', 17: 'Comparabilidad', 18: 'Secuencia cronológica', 19: 'Determinación del precio', 20: 'Procedimiento utilizado', 21: 'Procedencia jurídica', 22: 'Fundamentación', 23: 'Motivación', 24: 'Excepción a licitación', 25: 'Competencia para autorizar', 26: 'Intervención colegiada', 27: 'Plazos y formalidades', 28: 'Personalidad jurídica', 29: 'Objeto social y actividad', 30: 'Capacidad técnica', 31: 'Experiencia', 32: 'Recursos humanos', 33: 'Especialización del personal', 34: 'Capacidad material', 35: 'Adjudicación frente a contrato', 36: 'Facultades de firmantes', 37: 'Objeto contractual', 38: 'Monto', 39: 'Vigencia y plazos', 40: 'Entregables', 41: 'Condiciones de pago', 42: 'Administrador y supervisor', 43: 'Garantía de cumplimiento', 44: 'Otras garantías', 45: 'Penas convencionales', 46: 'Deductivas', 47: 'Inicio efectivo', 48: 'Programa de trabajo', 49: 'Actividades ejecutadas', 50: 'Cumplimiento de plazos', 51: 'Personal participante', 52: 'Administración contractual', 53: 'Incidencias', 54: 'Existencia de entregables', 55: 'Correspondencia técnica', 56: 'Integridad', 57: 'Oportunidad', 58: 'Evidencia de ejecución', 59: 'Consistencia documental', 60: 'Trazabilidad', 61: 'Existencia y formalización', 62: 'Justificación de la modificación', 63: 'Procedencia jurídica', 64: 'Efectos sobre condiciones', 65: 'Recepción formal', 66: 'Aceptación y conformidad', 67: 'Cumplimiento frente a factura', 68: 'Trazabilidad del pago', 69: 'Incumplimientos y consecuencias', 70: 'Cierre y evaluación integral'}
RUBROS=[(1, 'Planeación y justificación', 'Planeación', (1, 8)), (2, 'Programación y presupuesto', 'Presupuesto', (8, 12)), (3, 'Investigación de mercado', 'Inv. de mercado', (12, 20)), (4, 'Procedimiento de contratación', 'Procedimiento', (20, 28)), (5, 'Capacidad del proveedor', 'Capacidad prov.', (28, 35)), (6, 'Formalización contractual', 'Formalización', (35, 43)), (7, 'Garantías y sanciones', 'Garantías', (43, 47)), (8, 'Ejecución y administración', 'Ejecución', (47, 54)), (9, 'Entregables y evidencia material', 'Entregables', (54, 61)), (10, 'Modificaciones contractuales', 'Modificaciones', (61, 65)), (11, 'Recepción, facturación y pago', 'Recep. y pago', (65, 69)), (12, 'Incumplimiento, cierre y riesgo', 'Cierre', (69, 71))]  # id, nombre, nombre corto, (primer punto, último+1)
PRUEBAS=[('B.0', 'Tipo y alcance'), ('B.1', 'Integridad del legajo'), ('B.2', 'Cronología maestra'), ('B.3', 'Cálculos'), ('B.3 bis', 'Registro frente a CFDI'), ('B.4', 'Cruce de identidades'), ('B.5', 'Versiones y plantillas'), ('B.5 bis', 'Escritos redactados por el ente'), ('B.6', 'Firmas y suplencias'), ('B.7', 'Segregación de funciones'), ('B.8', 'Capa externa'), ('B.9', 'Modificaciones')]

# A.8: riesgo por defecto de los puntos «No acreditado»
A8={7:'Bajo',13:'Bajo',17:'Bajo',31:'Bajo',32:'Bajo',33:'Bajo',46:'Bajo',51:'Bajo',53:'Bajo',
    5:'Medio',12:'Medio',14:'Medio',15:'Medio',16:'Medio',19:'Medio',29:'Medio',30:'Medio',34:'Medio',45:'Medio',50:'Medio',55:'Medio',56:'Medio',57:'Medio',69:'Medio'}
A8_ALTO_CON_ALUSION=[47,49,54,58,60,68,70]   # Alto solo con alusión citada (B.0), salvo 49/68 que la ficha fija
# A.9: etapa de cada punto (rangos) para la marca «fuera del alcance documental»
A9_ETAPAS=[((1,4),'planeacion'),((5,5),'planeacion_original'),((6,6),'planeacion'),((7,7),'planeacion_original'),((8,11),'planeacion'),((12,17),'mercado'),((18,18),'transversal'),((19,19),'mercado'),((20,27),'procedimiento'),((28,28),'personalidad'),((29,34),'capacidad'),((35,44),'formalizacion'),((45,46),'clausulado_original'),((47,51),'ejecucion'),((52,52),'administracion'),((53,53),'ejecucion'),((54,58),'entregables'),((59,59),'transversal'),((60,60),'entregables'),((61,64),'modificaciones'),((65,68),'recepcion_pago'),((69,70),'cierre')]
PUNTOS_SIEMPRE_EN_ALCANCE=(18,59)
RIESGOS=['Bajo','Medio','Alto','Crítico']
RESULTADOS=['Cumple','Cumple parcialmente','No cumple','No acreditado','No aplica']
ESTADOS_PRUEBA=['sin observación','observación','hallazgo','pendiente']
